"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-07 17:39:02.540404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('startups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('allocated_seats', sa.Integer(), nullable=False),
    sa.Column('monthly_rate_per_seat', sa.Float(), nullable=False),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_startups_id'), 'startups', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_oauth_id'), 'users', ['oauth_id'], unique=False)
    op.create_index('ix_users_oauth_provider_oauth_id', 'users', ['oauth_provider', 'oauth_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('employees',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_startup_id'), 'employees', ['startup_id'], unique=False)
    op.create_table('floors',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floors_building_id'), 'floors', ['building_id'], unique=False)
    op.create_index(op.f('ix_floors_id'), 'floors', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('startup_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_type', sa.Enum('REALLOCATION', 'EXPANSION', 'REDUCTION', 'OPTIMIZATION', name='recommendationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='recommendationpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'IMPLEMENTED', name='recommendationstatus'), nullable=False),
    sa.Column('impact_seats', sa.Integer(), nullable=True),
    sa.Column('impact_revenue', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_startup_id'), 'recommendations', ['startup_id'], unique=False)
    op.create_table('occupancy_snapshots',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('floor_id', sa.UUID(), nullable=True),
    sa.Column('startup_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('occupied_seats', sa.Integer(), nullable=False),
    sa.Column('occupancy_rate', sa.Float(), nullable=False),
    sa.Column('period_type', sa.Enum('MINUTE_5', 'MINUTE_15', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', name='periodtype'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupancy_snapshots_building_id'), 'occupancy_snapshots', ['building_id'], unique=False)
    op.create_index('ix_occupancy_snapshots_building_time', 'occupancy_snapshots', ['building_id', 'snapshot_time'], unique=False)
    op.create_index(op.f('ix_occupancy_snapshots_floor_id'), 'occupancy_snapshots', ['floor_id'], unique=False)
    op.create_index(op.f('ix_occupancy_snapshots_id'), 'occupancy_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_occupancy_snapshots_snapshot_time'), 'occupancy_snapshots', ['snapshot_time'], unique=False)
    op.create_index(op.f('ix_occupancy_snapshots_startup_id'), 'occupancy_snapshots', ['startup_id'], unique=False)
    op.create_index('ix_occupancy_snapshots_startup_time', 'occupancy_snapshots', ['startup_id', 'snapshot_time'], unique=False)
    op.create_table('zones',
    sa.Column('floor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zone_type', sa.Enum('OPEN', 'PRIVATE', 'MEETING', 'COMMON', name='zonetype'), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_floor_id'), 'zones', ['floor_id'], unique=False)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_table('cameras',
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stream_url', sa.String(length=500), nullable=False),
    sa.Column('floor_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resolution_width', sa.Integer(), nullable=True),
    sa.Column('resolution_height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_building_id'), 'cameras', ['building_id'], unique=False)
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('seats',
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('seat_label', sa.String(length=50), nullable=False),
    sa.Column('x_coordinate', sa.Float(), nullable=True),
    sa.Column('y_coordinate', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'seat_label', name='uq_seats_zone_label')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_index(op.f('ix_seats_zone_id'), 'seats', ['zone_id'], unique=False)
    op.create_table('occupancy_events',
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OCCUPIED', 'VACANT', 'UNKNOWN', name='occupancystatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('person_bbox', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_occupancy_events_camera_detected', 'occupancy_events', ['camera_id', 'detected_at'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_occupancy_events_camera_id'), 'occupancy_events', ['camera_id'], unique=False)
    op.create_index('ix_occupancy_events_detected_at', 'occupancy_events', ['detected_at'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_occupancy_events_id'), 'occupancy_events', ['id'], unique=False)
    op.create_index('ix_occupancy_events_seat_detected', 'occupancy_events', ['seat_id', 'detected_at'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_occupancy_events_seat_id'), 'occupancy_events', ['seat_id'], unique=False)
    op.create_table('seat_allocations',
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deallocated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_allocations_id'), 'seat_allocations', ['id'], unique=False)
    op.create_index('ix_seat_allocations_seat_active', 'seat_allocations', ['seat_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_seat_allocations_seat_id'), 'seat_allocations', ['seat_id'], unique=False)
    op.create_index('ix_seat_allocations_startup_active', 'seat_allocations', ['startup_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_seat_allocations_startup_id'), 'seat_allocations', ['startup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_allocations_startup_id'), table_name='seat_allocations')
    op.drop_index('ix_seat_allocations_startup_active', table_name='seat_allocations')
    op.drop_index(op.f('ix_seat_allocations_seat_id'), table_name='seat_allocations')
    op.drop_index('ix_seat_allocations_seat_active', table_name='seat_allocations')
    op.drop_index(op.f('ix_seat_allocations_id'), table_name='seat_allocations')
    op.drop_table('seat_allocations')
    op.drop_index(op.f('ix_occupancy_events_seat_id'), table_name='occupancy_events')
    op.drop_index('ix_occupancy_events_seat_detected', table_name='occupancy_events', postgresql_using='btree')
    op.drop_index(op.f('ix_occupancy_events_id'), table_name='occupancy_events')
    op.drop_index('ix_occupancy_events_detected_at', table_name='occupancy_events', postgresql_using='btree')
    op.drop_index(op.f('ix_occupancy_events_camera_id'), table_name='occupancy_events')
    op.drop_index('ix_occupancy_events_camera_detected', table_name='occupancy_events', postgresql_using='btree')
    op.drop_table('occupancy_events')
    op.drop_index(op.f('ix_seats_zone_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_building_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_floor_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index('ix_occupancy_snapshots_startup_time', table_name='occupancy_snapshots')
    op.drop_index(op.f('ix_occupancy_snapshots_startup_id'), table_name='occupancy_snapshots')
    op.drop_index(op.f('ix_occupancy_snapshots_snapshot_time'), table_name='occupancy_snapshots')
    op.drop_index(op.f('ix_occupancy_snapshots_id'), table_name='occupancy_snapshots')
    op.drop_index(op.f('ix_occupancy_snapshots_floor_id'), table_name='occupancy_snapshots')
    op.drop_index('ix_occupancy_snapshots_building_time', table_name='occupancy_snapshots')
    op.drop_index(op.f('ix_occupancy_snapshots_building_id'), table_name='occupancy_snapshots')
    op.drop_table('occupancy_snapshots')
    op.drop_index(op.f('ix_recommendations_startup_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_floors_id'), table_name='floors')
    op.drop_index(op.f('ix_floors_building_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_employees_startup_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_oauth_provider_oauth_id', table_name='users')
    op.drop_index(op.f('ix_users_oauth_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_startups_id'), table_name='startups')
    op.drop_table('startups')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
